### PR TITLE
Update dependencies, fix tests that were allowed to fail

### PR DESCRIPTION
**Pull request by PavelJurasek**
- don't use min-stability: dev
- remove StrictObject
- higher PHPStan level

### CODE REVIEW

**Comment by PavelJurasek** [comment]
New 3.0 release is necessary in order to be able to make stable kdyby/annotations and kdyby/doctrine versions.

**Comment by PavelJurasek** [comment]
I now actually see why some things are the way they are. Minimum stability shouldn't have been removed, including travis setup. I'll leave the PR open for now and rework later.

**Comment by haltuf** [comment]
I need the new version of Kdyby/DoctrineCache to move on with updating Kdyby/Doctrine to Nette v 3.0
This PR is here for 6 weeks. Who's currently the master of this repo to merge this PR and create new version?

**Comment by enumag** [comment]
Most likely irrelevant after #22. If there is anything left in this PR you'd still like merged, make a new PR and ping me there. Thank you.

**Pull request closed without merging**
