### PR TITLE
Make Nette 3.0 compatible

### PR DESCRIPTION
**Pull request by TomasVotruba**

### CODE REVIEW

**Comment by enumag** [comment]
Need to update composer and travis.

**Comment by TomasVotruba** [comment]
This only hot fix PR.

It would actually mean lot of Kdyby packages refactoring, dropping deprecated packages, bumping to PHP 7 etc. I'll let that to @fprochazka

**Comment by Majkl578** [comment]
The problem with this is that it is **not** possible to keep the package backward compatible, due to the nature of the changes and the fact that parameter types are invariant (to be contravariant in PHP 7.2),

**Comment by TomasVotruba** [comment]
Yes, this requires bump to PHP 7.1.

**Comment by enumag** [comment]
@Majkl578 

> (to be contravariant in PHP 7.2)

I don't understand. Seems like you're talking about something new in PHP 7.2. Can you give me a link to the RFC you're hinting?

**Comment by Majkl578** [comment]
https://wiki.php.net/rfc/parameter-no-type-variance

**Pull request closed without merging**
