### PR TITLE
Support caching "empty" values

### PR DESCRIPTION
**Pull request by Andrewsville**
Support for caching "empty" values, mainly empty arrays.

### CODE REVIEW

**Comment by enumag** [comment]
Could you add a test? I believe it is very important in this case.

**Comment by fprochazka** [comment]
Very nice catch! But I'm gonna need a test case for this. I might have some time at the weekend, so if you won't do it, hopefuly I'll have the time.

**Comment by Andrewsville** [comment]
Well, my knowledge of Nette tester is exactly zero but I'll try to make a simple test.

**Comment by fprochazka** [comment]
@Andrewsville tester is easy, if you could create the test, that would be awesome! :)

**Comment by enumag** [comment]
ping @Andrewsville

**Comment by fprochazka** [comment]
I've added the test and merged. Thanks!

Please test it if possible and report back.

**Comment by enumag** [comment]
@fprochazka I think we should include this bugfix to older branches as well (for usage with Nette 2.2). Not that I need it personally though.

**Comment by fprochazka** [comment]
True

**Pull request closed without merging**
