### PR TITLE
Memcached support

### PR DESCRIPTION
**Pull request by jasin755**

### CODE REVIEW

**Comment by enumag** [comment]
Could you add a test? https://github.com/Kdyby/DoctrineCache/blob/master/tests/KdybyTests/DoctrineCache/Extension.phpt#L48

**Comment by jasin755** [comment]
Yes I can. I will try tomorrow

**Comment by jasin755** [comment]
I watch the tests probably are using Nette Tester. I have no experience with it. I use pure PHPUnit. I tried to install Nette Tester and run as "../vendor/bin/tester tests" and both tests fail (FAILED: Kdyby\Doctrine\Extension. | KdybyTests/DoctrineCache/Extension.phpt) Without more detailed information :(

**Comment by fprochazka** [comment]
@jasin755 all you really need to do is run `composer install` in the cloned project and then [run the command from travis.yml](https://github.com/Kdyby/DoctrineCache/blob/0655aaee29ee94d4a38d45d0de15ad4c94b5f946/.travis.yml#L35)

**Comment by jasin755** [comment]
It's not that easy. I added a line to the php.ini "extension = memcached.so" but PHP7 is not supporting the original memcache.so.

**Comment by fprochazka** [comment]
Thank you

**Pull request merged**
