### PR TITLE
Add alias for apcu cache

### PR DESCRIPTION
**Pull request by jiripudil**
doctrine/cache added ApcuCache driver in 1.6. I thought it would be nice to have a config shortcut for the driver.

### CODE REVIEW

**Comment by enumag** [comment]
Add a test please. https://github.com/Kdyby/DoctrineCache/blob/master/tests/KdybyTests/DoctrineCache/Extension.phpt#L48

**Comment by jiripudil** [comment]
Oh. It seems that doctrine/cache 1.6.0 which added the apcu driver requires PHP >= 5.5, so 5.4 builds fail. What do you suggest? Should I split the test case and skip apcu test on 5.4? (And maybe separate memcache test for PHP 7 build while I'm at it?)

**Comment by enumag** [comment]
Hmm. I don't know how exactly skipping works in Nette/Tester so I'm not sure about the best solution.

ping @fprochazka

**Comment by fprochazka** [comment]
@jiripudil you can create `Extensions.php55.phpt`

```php
<?php

/**
 * @testcase
 * @phpversion 5.5
 */
```

and move it there

**Comment by fprochazka** [comment]
I'll fix the build and you can rebase on it then :)

**Comment by jiripudil** [comment]
Rebased :)

**Comment by fprochazka** [comment]
@jiripudil you're too fast :P I'm not done yet

**Comment by jiripudil** [comment]
:lol:

**Comment by enumag** [comment]
@jiripudil Don't forget to squash. :-)

**Comment by fprochazka** [comment]
@jiripudil not that I think about it more, having a separate file is not neccesary :) See the `testFunctionalityMemcache`

**Comment by fprochazka** [comment]
great :+1:

**Pull request merged**
